import { createContext, useState, useEffect } from "react";

const LanguageContext = createContext(null);
export default LanguageContext;

const translations = {
  use: {
    langLabel: "US",
    nav: {
      home: "Home",
      courses: "Courses",
      about: "About",
      contact: "Contact",
      becomeInstructor: "Become an Instructor",
    },
    hero: {
      heading: "Learn with expert anytime anywhere",
      para: "Our mission is to help people to find the best course online and learn with expert anytime, anywhere.",
      btnCreateAccount: "Create Account",
    },
    category: {
      heading: "Browse top category",
      coursesSuffix: "Courses",
      moreText: "We have more category & subcategory.",
      browseAll: "Browse All",
    },
    popularCourses: {
      heading: "Popular Courses",
      subheading: "Explore our most enrolled courses",
    },
    instructors: {
      heading: "Meet Our Instructors",
      subheading: "Learn from the best in the industry",
    },
    testimonials: {
      heading: "What Our Students Say",
      subheading: "Read reviews from our community",
    },
    newsletter: {
      heading: "Subscribe to Our Newsletter",
      subheading: "Get the latest updates on new courses and promotions",
      placeholder: "Enter your email",
      btnSubscribe: "Subscribe",
    },
    footer: {
      about: "About",
      contact: "Contact",
      terms: "Terms & Conditions",
      privacy: "Privacy Policy",
      allRightsReserved: "All rights reserved.",
      quickLinks: "Quick Links",
      followUs: "Follow Us",
    },
    coursesPage: {
      heading: "All Courses",
      subheading: "Explore our collection of expert-led courses",
      searchPlaceholder: "Search courses...",
      allCategories: "All Categories",
      relevance: "Relevance",
      priceLow: "Price: Low to High",
      priceHigh: "Price: High to Low",
      highestRated: "Highest Rated",
      noResults: "No courses found. Try adjusting your filters.",
    },
    courseDetail: {
      students: "students",
      instructor: "Instructor",
      enrollNow: "Enroll Now",
      inCart: "In Cart",
      addToWishlist: "Add to Wishlist",
      inWishlist: "In Wishlist",
      curriculum: "Curriculum",
      yourInstructor: "Your Instructor",
      notFound: "Course not found",
    },
    about: {
      heading: "About E-tutor",
      subheading: "Empowering learners worldwide",
      para1: "E-tutor is a leading online learning platform dedicated to providing high-quality education to students around the globe. Our mission is to make expert-led courses accessible to everyone, anywhere.",
      para2: "Founded in 2020, we have grown to serve over 100,000 students with courses spanning web development, data science, design, business, and more.",
      ourMission: "Our Mission",
      missionText: "To democratize education by making expert knowledge accessible to learners worldwide through affordable, high-quality online courses.",
      ourVision: "Our Vision",
      visionText: "To become the world's most trusted online learning platform, empowering millions to achieve their educational and career goals.",
    },
    contact: {
      heading: "Get In Touch",
      subheading: "We'd love to hear from you",
      ourInfo: "Our Information",
      address: "123 Education Street, Learning City, LC 45678",
      phone: "+1 (555) 123-4567",
      email: "support@e-tutor.com",
      yourName: "Your Name",
      yourEmail: "Your Email",
      message: "Message",
      messagePlaceholder: "Write your message here...",
      sendMessage: "Send Message",
      messageSent: "Message sent successfully!",
    },
    login: {
      heading: "Welcome Back",
      subheading: "Sign in to your account to continue learning.",
      email: "Email",
      emailPlaceholder: "Enter your email",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      btnLogin: "Sign In",
      noAccount: "Don't have an account?",
      signup: "Sign up here",
      error: "Invalid email or password",
    },
    signup: {
      heading: "E-tutor",
      subheading: "Create your account and start learning today.",
      fullName: "Full Name",
      namePlaceholder: "Enter your name",
      email: "Email",
      emailPlaceholder: "Enter your email",
      password: "Password",
      passwordPlaceholder: "Create a password",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "Confirm your password",
      btnCreate: "Create Account",
      haveAccount: "Already have an account?",
      signin: "Sign in here",
      errorAllFields: "Please fill in all fields",
      errorPasswords: "Passwords do not match",
    },
    instructorSignup: {
      heading: "Become an Instructor",
      subheading: "Share your knowledge and inspire learners worldwide.",
      fullName: "Full Name",
      namePlaceholder: "Enter your name",
      email: "Email",
      emailPlaceholder: "Enter your email",
      password: "Password",
      passwordPlaceholder: "Create a password",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "Confirm your password",
      title: "Title / Expertise",
      titlePlaceholder: "e.g. Senior Full-Stack Developer",
      expertise: "Primary Expertise Area",
      expertisePlaceholder: "e.g. Web Development, Data Science",
      bio: "Bio",
      bioPlaceholder: "Tell students about your experience and background...",
      btnCreate: "Create Instructor Account",
      notTeaching: "Not looking to teach?",
      signupStudent: "Sign up as a student",
      errorAllFields: "Please fill in all fields",
      errorPasswords: "Passwords do not match",
      errorBio: "Bio must be at least 20 characters",
      successTitle: "Welcome, Instructor!",
      successText: "Your instructor account has been created successfully. Redirecting to your dashboard...",
    },
    dashboard: {
      heading: "Dashboard",
      myCourses: "My Courses",
      cart: "Cart",
      wishlist: "Wishlist",
      removeFromCart: "Remove",
      proceedToCheckout: "Proceed to Checkout",
      total: "Total",
      emptyCourses: "You haven't enrolled in any courses yet.",
      emptyCart: "Your cart is empty.",
      emptyWishlist: "Your wishlist is empty.",
      browseCourses: "Browse Courses",
    },
    notFound: {
      heading: "404",
      subheading: "Page Not Found",
      text: "The page you're looking for doesn't exist.",
      goHome: "Go Home",
    },
  },
  eng: {
    langLabel: "UK",
    nav: {
      home: "Home",
      courses: "Courses",
      about: "About",
      contact: "Contact",
      becomeInstructor: "Become an Instructor",
    },
    hero: {
      heading: "Learn with an expert anytime, anywhere",
      para: "Our mission is to help people find the best course online and learn with an expert anytime, anywhere.",
      btnCreateAccount: "Create Account",
    },
    category: {
      heading: "Browse Top Categories",
      coursesSuffix: "Courses",
      moreText: "We have more categories and subcategories.",
      browseAll: "Browse All",
    },
    popularCourses: {
      heading: "Popular Courses",
      subheading: "Explore our most enrolled courses",
    },
    instructors: {
      heading: "Meet Our Instructors",
      subheading: "Learn from the best in the industry",
    },
    testimonials: {
      heading: "What Our Students Say",
      subheading: "Read reviews from our community",
    },
    newsletter: {
      heading: "Subscribe to Our Newsletter",
      subheading: "Get the latest updates on new courses and promotions",
      placeholder: "Enter your e-mail",
      btnSubscribe: "Subscribe",
    },
    footer: {
      about: "About",
      contact: "Contact",
      terms: "Terms & Conditions",
      privacy: "Privacy Policy",
      allRightsReserved: "All rights reserved.",
      quickLinks: "Quick Links",
      followUs: "Follow Us",
    },
    coursesPage: {
      heading: "All Courses",
      subheading: "Explore our collection of expert-led courses",
      searchPlaceholder: "Search courses...",
      allCategories: "All Categories",
      relevance: "Relevance",
      priceLow: "Price: Low to High",
      priceHigh: "Price: High to Low",
      highestRated: "Highest Rated",
      noResults: "No courses found. Try adjusting your filters.",
    },
    courseDetail: {
      students: "students",
      instructor: "Instructor",
      enrollNow: "Enrol Now",
      inCart: "In Basket",
      addToWishlist: "Add to Wishlist",
      inWishlist: "In Wishlist",
      curriculum: "Curriculum",
      yourInstructor: "Your Instructor",
      notFound: "Course not found",
    },
    about: {
      heading: "About E-tutor",
      subheading: "Empowering learners worldwide",
      para1: "E-tutor is a leading online learning platform dedicated to providing high-quality education to students around the globe. Our mission is to make expert-led courses accessible to everyone, anywhere.",
      para2: "Founded in 2020, we have grown to serve over 100,000 students with courses spanning web development, data science, design, business, and more.",
      ourMission: "Our Mission",
      missionText: "To democratise education by making expert knowledge accessible to learners worldwide through affordable, high-quality online courses.",
      ourVision: "Our Vision",
      visionText: "To become the world's most trusted online learning platform, empowering millions to achieve their educational and career goals.",
    },
    contact: {
      heading: "Get In Touch",
      subheading: "We'd love to hear from you",
      ourInfo: "Our Information",
      address: "123 Education Street, Learning City, LC 45678",
      phone: "+44 (0) 20 7123 4567",
      email: "support@e-tutor.com",
      yourName: "Your Name",
      yourEmail: "Your E-mail",
      message: "Message",
      messagePlaceholder: "Write your message here...",
      sendMessage: "Send Message",
      messageSent: "Message sent successfully!",
    },
    login: {
      heading: "Welcome Back",
      subheading: "Sign in to your account to continue learning.",
      email: "E-mail",
      emailPlaceholder: "Enter your e-mail",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      btnLogin: "Sign In",
      noAccount: "Don't have an account?",
      signup: "Sign up here",
      error: "Invalid e-mail or password",
    },
    signup: {
      heading: "E-tutor",
      subheading: "Create your account and start learning today.",
      fullName: "Full Name",
      namePlaceholder: "Enter your name",
      email: "E-mail",
      emailPlaceholder: "Enter your e-mail",
      password: "Password",
      passwordPlaceholder: "Create a password",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "Confirm your password",
      btnCreate: "Create Account",
      haveAccount: "Already have an account?",
      signin: "Sign in here",
      errorAllFields: "Please fill in all fields",
      errorPasswords: "Passwords do not match",
    },
    instructorSignup: {
      heading: "Become an Instructor",
      subheading: "Share your knowledge and inspire learners worldwide.",
      fullName: "Full Name",
      namePlaceholder: "Enter your name",
      email: "E-mail",
      emailPlaceholder: "Enter your e-mail",
      password: "Password",
      passwordPlaceholder: "Create a password",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "Confirm your password",
      title: "Title / Expertise",
      titlePlaceholder: "e.g. Senior Full-Stack Developer",
      expertise: "Primary Expertise Area",
      expertisePlaceholder: "e.g. Web Development, Data Science",
      bio: "Biography",
      bioPlaceholder: "Tell students about your experience and background...",
      btnCreate: "Create Instructor Account",
      notTeaching: "Not looking to teach?",
      signupStudent: "Sign up as a student",
      errorAllFields: "Please fill in all fields",
      errorPasswords: "Passwords do not match",
      errorBio: "Biography must be at least 20 characters",
      successTitle: "Welcome, Instructor!",
      successText: "Your instructor account has been created successfully. Redirecting to your dashboard...",
    },
    dashboard: {
      heading: "Dashboard",
      myCourses: "My Courses",
      cart: "Basket",
      wishlist: "Wishlist",
      removeFromCart: "Remove",
      proceedToCheckout: "Proceed to Checkout",
      total: "Total",
      emptyCourses: "You haven't enrolled in any courses yet.",
      emptyCart: "Your basket is empty.",
      emptyWishlist: "Your wishlist is empty.",
      browseCourses: "Browse Courses",
    },
    notFound: {
      heading: "404",
      subheading: "Page Not Found",
      text: "The page you're looking for doesn't exist.",
      goHome: "Go Home",
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("e-tutor-language") || "use";
  });

  useEffect(() => {
    localStorage.setItem("e-tutor-language", language);
  }, [language]);

  const t = translations[language] || translations.use;

  const setLang = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, t, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
};
